sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1

language: c

compiler:
  - gcc
  - clang

services:
  - docker

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    - reflector
    # aur
    - archey3-git
  script:
    - "sudo archey3"
    - "reflector --verbose -l 20 --sort rate -p https"
    - "echo $CC"
    - "touch test_file"

script:
  - "bash ./arch-travis-docker.sh"
  - "ls -l"
